version: '3'

volumes:
  # These are for the actual web server
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  # These are for the additional matomo web analytics service
  # https://matomo.org/docs/installation/
  # https://github.com/matomo-org/docker/blob/master/.examples/apache/docker-compose.yml
  production_mariadb_data: {}
  production_matomo: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: electronicheart_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    volumes:
      # The build process can take quite a while if many of the libraries have to be compiled first (which is the case
      # when attempting to run the thing on a non standard architecture like the raspberry pi). A lot of these build
      # results are saved in /tmp. This will hopefully persist these between builds and speed up the process?
      - /tmp:/tmp
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: electronicheart_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: electronicheart_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:5.0

  # == MATOMO WEB ANALYTICS ==

  mariadb:
    # I am intending to deploy this on the raspberry pi and the default mariadb image does not support the raspi ARM
    # architecture, but apparently this version does so we are using this one.
    image: webhippie/mariadb
    # command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - production_mariadb_data:/var/lib/mysql
    env_file:
      - .envs/.production/.matomo

  matomo:
    image: matomo
    restart: always
    volumes:
      - production_matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=mariadb
    env_file:
      - .envs/.production/.matomo
    ports:
      - "0.0.0.0:8080:80"

