# Generated by Django 3.0.10 on 2021-03-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210306_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
