# Generated by Django 3.0.10 on 2021-08-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210830_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hash_id',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
