# Generated by Django 3.0.10 on 2021-08-31 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20210831_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterNotebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(blank=True, default='', max_length=250)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(default='auto', max_length=250, unique=True)),
                ('content', models.TextField(default='')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next', models.URLField(blank=True, null=True)),
                ('previous', models.URLField(blank=True, null=True)),
                ('head_html', models.TextField(blank=True, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jupyter_notebooks', to=settings.AUTH_USER_MODEL)),
                ('html_file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='html_file', to='filer.File')),
                ('jupyter_file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='juypter_file', to='filer.File')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
