# Generated by Django 3.0.10 on 2021-09-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210901_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='jupyternotebook',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
