# Generated by Django 3.0.10 on 2021-09-03 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('blog', '0016_auto_20210902_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main title of the entry. Does not have to be unique', max_length=250)),
                ('subtitle', models.CharField(blank=True, default='', max_length=250)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('tutorial', 'Tutorial'), ('project', 'Project'), ('jupyter', 'Jupyter Notebook')], max_length=10)),
                ('slug', models.SlugField(default='auto', max_length=250, unique=True)),
                ('content', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next', models.URLField(blank=True, null=True)),
                ('previous', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JupyterNotebookExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_html', models.TextField(blank=True, null=True)),
                ('content_html', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jupyter', to='blog.Entry')),
                ('html_file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='html_file', to='filer.File')),
                ('jupyter_file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='jupyter_file', to='filer.File')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='thumbnail',
        ),
        migrations.DeleteModel(
            name='JupyterNotebook',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
