# Generated by Django 3.0.10 on 2021-09-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210903_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jupyternotebookextension',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jupyter', to='blog.Entry'),
        ),
    ]
