log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"

  web-secure:
    # https
    address: ":443"

  matomo-secure:
    address: ":8080"

  ftp-secure:
    # ftp
    address: ":21"

  media-secure:
    # http alternative
    address: ":81"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "jonseb1998@gmail.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-router:
      rule: 'Host(`{{ env "DJANGO_ALLOWED_HOSTS" }}`)'

      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: django

    web-secure-router:
      # rule: "Host(`electronic-heart.com`) || Host(`www.electronic-heart.com`)"
      #rule: "Host(`blog.electronic-heart.com`)"
      rule: 'Host(`{{ env "DJANGO_ALLOWED_HOSTS" }}`)'

      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    matomo-secure-router:
      rule: 'Host(`{{ env "DJANGO_ALLOWED_HOSTS" }}`)'

      entryPoints:
        - matomo-secure
      middlewares:
        - csrf
      service: matomo
      tls:
        certResolver: letsencrypt

    media-secure-router:
      rule: 'Host(`{{ env "DJANGO_ALLOWED_HOSTS" }}`)'

      entryPoints:
        - media-secure
      middlewares:
        - csrf
      service: media
      tls:
        certResolver: letsencrypt

    ftp-secure-router:
      rule: 'Host(`{{ env "DJANGO_ALLOWED_HOSTS" }}`)'

      entryPoints:
        - ftp-secure
      middlewares:
        - csrf
      service: ftp
      tls:
        certResolver: letsencrypt

  middlewares:
    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    matomo:
      loadBalancer:
        servers:
          - url: http://matomo:80

    media:
      loadBalancer:
        servers:
          - url: http://media:80

    ftp:
      loadBalancer:
        servers:
          - url: http://media:21

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
